services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xtremepush
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpunit:
    image: php:8.3-cli
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    entrypoint: ["./vendor/bin/phpunit"]

volumes:
  db_data:
